### ISSUE TITLE
Tabulation/TTLization runs out of heap space on very long texts

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/hocuspocus#67] opened 2016-05-31 13:02 UTC
Tabulation/TTLization runs out of heap space on very long texts. Longer than an Iliad, but shorter than an Iliad with each word citable.

**Comment by neelsmith** [comment] 2016-06-08 15:35
Not a bug, even if it's not the most desirable feature of the library.  Response:

1. hocuspocus supports in-memory tabulation/ttl'ziation (and therefore is reasonably fast)
2. options for handling very large texts:
    - set ginormous heap space when running
    - segment your text before tabulating/ttl'izing

Closing this issue out after our recent phone conversation.

**Closed by neelsmith** 2016-06-08 15:35 UTC
Labels: bug
